version: '3.8'

services:
  streamlit_app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fast_api
    container_name: streamlit_app

  fast_api:
    build: ./fast_api
    ports:
      - "8000:8000"
    container_name: fast_api
